server:
  port: 21002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:21000/eureka
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: Activity-Service
  data:
    mongodb:
      uri: mongodb://localhost:27017/ActivityDB
      database: ActivityDB



