server:
  port: 21003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:21000/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}

spring:
  application:
    name: AI-Service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessRecommendationDB
      database: fitnessRecommendationDB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking